export const FIND_ALL_PARCEL_REQUEST = 'FIND_ALL_PARCEL_REQUEST';
export const FIND_ALL_PARCEL_REQUEST_SUCCESS = 'FIND_ALL_PARCEL_REQUEST_SUCCESS';
export const FIND_ALL_PARCEL_REQUEST_FAIL = 'FIND_ALL_PARCEL_REQUEST_FAIL';

export const HANDLE_SHOW = 'HANDLE_SHOW';

export const CREATE_PARCEL_REQUEST = 'CREATE_PARCEL_REQUEST';
export const CREATE_PARCEL_REQUEST_SUCCESS = 'CREATE_PARCEL_REQUEST_SUCCESS';
export const CREATE_PARCEL_REQUEST_FAIL = 'CREATE_PARCEL_REQUEST_FAIL';